name: Org Membership Audit

on: 
  workflow_dispatch:

jobs:
  org_audit:
    name: Run Org Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Membership Audit Log Action
        uses: svanboxel/org-audit-action@master
        with:
          organization: 'octodemo'
          token: ${{ secrets.ORG_ADMIN_TOKEN }}
          issue: false
          samlIdentities: false
